project:
  type: website

website:
  title: "LASER"
  site-url: https://kayhryu89.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: members.qmd
        text: People
      - href: board.qmd
        text: Board

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
